from __future__ import annotations

from .. import db as _core

def find_ready_speaker_segment() -> dict[str, _core.Any] | None:
    with _core.connect() as conn:
        cur = _core._dict_cursor(conn)
        cur.execute(f"\n            SELECT seg.id, seg.task_id, seg.item_index\n            FROM speaker_segment seg FORCE INDEX (idx_speaker_segment_status_task_item)\n            JOIN task t ON t.id = seg.task_id\n            JOIN task vi ON vi.id = seg.task_id\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n             AND sp.sub_stage = CASE\n                   WHEN vi.task_type = 'narration' THEN %s\n                   WHEN vi.task_type IN (%s, %s) THEN %s\n                   WHEN vi.task_type = 'ppt' THEN %s\n                   ELSE %s\n                 END\n            WHERE seg.status = %s\n              AND sp.status IN (%s, %s)\n            ORDER BY COALESCE(t.priority, 1) DESC, seg.task_id ASC, seg.item_index ASC\n            LIMIT {_core.READY_SPEAKER_SEGMENT_CANDIDATE_LIMIT}\n            ", (_core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.SEGMENT_READY, _core.READY, _core.RUNNING))
        candidate_rows = cur.fetchall()
        if not candidate_rows:
            return None
        candidate_segment_ids = [int(row['id']) for row in candidate_rows]
        candidate_task_ids = sorted({str(row['task_id']) for row in candidate_rows})
        segment_placeholders = ', '.join(['%s'] * len(candidate_segment_ids))
        task_placeholders = ', '.join(['%s'] * len(candidate_task_ids))
        cur.execute(f"\n            SELECT seg.*,\n                   COALESCE(t.priority, 1) AS task_priority,\n                   vi.task_type AS task_type,\n                   sp.sub_stage AS speaker_sub_stage,\n                   proc.translation_json_path AS translation_json_path\n            FROM speaker_segment seg\n            JOIN task t ON t.id = seg.task_id\n            JOIN task vi ON vi.id = seg.task_id\n            LEFT JOIN task_processing proc ON proc.task_id = seg.task_id\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n             AND sp.sub_stage = CASE\n                   WHEN vi.task_type = 'narration' THEN %s\n                   WHEN vi.task_type IN (%s, %s) THEN %s\n                   WHEN vi.task_type = 'ppt' THEN %s\n                   ELSE %s\n                 END\n            JOIN (\n                SELECT seg_stats.task_id,\n                       COUNT(*) AS total_segments,\n                       SUM(CASE WHEN seg_stats.status <> %s THEN 1 ELSE 0 END) AS remaining_segments\n                FROM speaker_segment seg_stats\n                WHERE seg_stats.task_id IN ({task_placeholders})\n                GROUP BY seg_stats.task_id\n            ) stats ON stats.task_id = seg.task_id\n            WHERE sp.status IN (%s, %s)\n              AND seg.status = %s\n              AND seg.id IN ({segment_placeholders})\n            ORDER BY\n              COALESCE(t.priority, 1) DESC,\n              CASE WHEN sp.status = %s THEN 0 ELSE 1 END,\n              CASE\n                WHEN sp.status = %s THEN stats.remaining_segments\n                ELSE stats.total_segments\n              END ASC,\n              seg.task_id ASC,\n              seg.item_index ASC\n            LIMIT 1\n            ", (_core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.SEGMENT_SUCCESS, *candidate_task_ids, _core.READY, _core.RUNNING, _core.SEGMENT_READY, *candidate_segment_ids, _core.RUNNING, _core.RUNNING))
        return _core.task_info.merge_into(cur.fetchone(), fields=_core.SPEAKER_TASK_INFO_FIELDS)

def claim_speaker_segment(segment_id: int) -> dict[str, _core.Any] | None:
    operator = _core._operator_value()
    with _core.connect() as conn:
        cur = conn.cursor()
        _core._ensure_operator_columns(cur, ('speaker', 'speaker_segment'))
        cur.execute("\n            UPDATE speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n             AND sp.sub_stage = CASE\n                   WHEN vi.task_type = 'narration' THEN %s\n                   WHEN vi.task_type IN (%s, %s) THEN %s\n                   WHEN vi.task_type = 'ppt' THEN %s\n                   ELSE %s\n                 END\n            SET seg.status = %s,\n                seg.attempt_count = seg.attempt_count + 1,\n                seg.started_at = COALESCE(seg.started_at, NOW()),\n                seg.error_message = NULL,\n                seg.`operator` = %s\n            WHERE seg.id = %s\n              AND seg.status = %s\n              AND sp.status IN (%s, %s)\n            ", (_core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.SEGMENT_RUNNING, operator, segment_id, _core.SEGMENT_READY, _core.READY, _core.RUNNING))
        if cur.rowcount != 1:
            conn.commit()
            return None
        cur = _core._dict_cursor(conn)
        cur.execute("\n            SELECT seg.*,\n                   vi.task_type AS task_type,\n                   sp.sub_stage AS speaker_sub_stage,\n                   proc.translation_json_path AS translation_json_path\n            FROM speaker_segment seg\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n            JOIN task vi ON vi.id = seg.task_id\n            LEFT JOIN task_processing proc ON proc.task_id = seg.task_id\n            WHERE seg.id = %s\n            ", (segment_id,))
        row = cur.fetchone()
        if row:
            cur = conn.cursor()
            cur.execute("\n                UPDATE distributor_task_stages\n                SET status = %s,\n                    started_at = COALESCE(started_at, NOW()),\n                    error_message = NULL,\n                    `operator` = %s\n                WHERE task_id = %s AND stage_name = 'speaker' AND sub_stage = %s AND status = %s\n                ", (_core.RUNNING, operator, row['task_id'], row['speaker_sub_stage'], _core.READY))
        conn.commit()
        return _core.task_info.merge_into(row, fields=_core.SPEAKER_TASK_INFO_FIELDS)

def recycle_stale_speaker_segments() -> tuple[int, list[str]]:
    timeout_seconds = _core.SEGMENT_RUNNING_TIMEOUT_SECONDS
    narration_timeout_seconds = _core.NARRATION_SEGMENT_RUNNING_TIMEOUT_SECONDS
    message = f'speaker segment timed out after {timeout_seconds}s; retrying'
    narration_message = f'speaker narration segment timed out after {narration_timeout_seconds}s; retrying'
    exhausted_message = f'speaker segment timed out after {timeout_seconds}s; max attempts exhausted'
    narration_exhausted_message = f'speaker narration segment timed out after {narration_timeout_seconds}s; max attempts exhausted'
    failed_recycle_message = 'speaker failed segment recycled; retrying'
    with _core.connect() as conn:
        cur = _core._dict_cursor(conn)
        cur.execute("\n            SELECT DISTINCT seg.task_id\n            FROM speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            WHERE seg.status = %s\n              AND seg.attempt_count >= seg.max_attempts\n              AND seg.started_at IS NOT NULL\n              AND TIMESTAMPDIFF(SECOND, seg.started_at, NOW()) >\n                  CASE WHEN vi.task_type = 'narration' THEN %s ELSE %s END\n            ", (_core.SEGMENT_RUNNING, narration_timeout_seconds, timeout_seconds))
        exhausted_task_ids = [str(row['task_id']) for row in cur.fetchall()]
        cur = conn.cursor()
        cur.execute("\n            UPDATE speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            SET seg.status = %s,\n                seg.error_message = CASE WHEN vi.task_type = 'narration' THEN %s ELSE %s END,\n                seg.started_at = NULL,\n                seg.completed_at = NULL,\n                seg.`operator` = NULL\n            WHERE seg.status = %s\n              AND seg.attempt_count < seg.max_attempts\n              AND seg.started_at IS NOT NULL\n              AND TIMESTAMPDIFF(SECOND, seg.started_at, NOW()) >\n                  CASE WHEN vi.task_type = 'narration' THEN %s ELSE %s END\n            ", (_core.SEGMENT_READY, narration_message, message, _core.SEGMENT_RUNNING, narration_timeout_seconds, timeout_seconds))
        retried = cur.rowcount
        cur.execute("\n            UPDATE speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            SET seg.status = %s,\n                seg.error_message = CASE WHEN vi.task_type = 'narration' THEN %s ELSE %s END,\n                seg.completed_at = NOW()\n            WHERE seg.status = %s\n              AND seg.attempt_count >= seg.max_attempts\n              AND seg.started_at IS NOT NULL\n              AND TIMESTAMPDIFF(SECOND, seg.started_at, NOW()) >\n                  CASE WHEN vi.task_type = 'narration' THEN %s ELSE %s END\n            ", (_core.SEGMENT_FAILED, narration_exhausted_message, exhausted_message, _core.SEGMENT_RUNNING, narration_timeout_seconds, timeout_seconds))
        failed = cur.rowcount
        cur = _core._dict_cursor(conn)
        cur.execute("\n            SELECT DISTINCT seg.task_id\n            FROM speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n             AND sp.sub_stage = CASE\n                   WHEN vi.task_type = 'narration' THEN %s\n                   WHEN vi.task_type IN (%s, %s) THEN %s\n                   WHEN vi.task_type = 'ppt' THEN %s\n                   ELSE %s\n                 END\n            WHERE seg.status = %s\n              AND sp.status IN (%s, %s, %s)\n              AND (\n                  seg.error_message IS NULL\n                  OR seg.error_message NOT LIKE 'translator api task failed:%%'\n              )\n            ", (_core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.SEGMENT_FAILED, _core.READY, _core.RUNNING, _core.FAILED))
        recycled_failed_task_ids = [str(row['task_id']) for row in cur.fetchall()]
        cur = conn.cursor()
        cur.execute("\n            UPDATE speaker_segment seg\n            JOIN task vi ON vi.id = seg.task_id\n            JOIN distributor_task_stages sp\n              ON sp.task_id = seg.task_id\n             AND sp.stage_name = 'speaker'\n             AND sp.sub_stage = CASE\n                   WHEN vi.task_type = 'narration' THEN %s\n                   WHEN vi.task_type IN (%s, %s) THEN %s\n                   WHEN vi.task_type = 'ppt' THEN %s\n                   ELSE %s\n                 END\n            SET seg.status = %s,\n                seg.attempt_count = 0,\n                seg.error_message = %s,\n                seg.started_at = NULL,\n                seg.completed_at = NULL,\n                seg.`operator` = NULL\n            WHERE seg.status = %s\n              AND sp.status IN (%s, %s, %s)\n              AND (\n                  seg.error_message IS NULL\n                  OR seg.error_message NOT LIKE 'translator api task failed:%%'\n              )\n            ", (_core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.SEGMENT_READY, failed_recycle_message, _core.SEGMENT_FAILED, _core.READY, _core.RUNNING, _core.FAILED))
        recycled_failed = cur.rowcount
        if recycled_failed_task_ids:
            placeholders = ', '.join(['%s'] * len(recycled_failed_task_ids))
            cur.execute(f"\n                UPDATE distributor_task_stages sp\n                SET sp.status = %s,\n                    sp.completed_at = NULL,\n                    sp.error_message = NULL\n                WHERE sp.task_id IN ({placeholders})\n                  AND sp.stage_name = 'speaker'\n                  AND sp.sub_stage = CASE\n                        WHEN EXISTS (\n                          SELECT 1 FROM task vi\n                          WHERE vi.id = sp.task_id AND vi.task_type = 'narration'\n                        ) THEN %s\n                        WHEN EXISTS (\n                          SELECT 1 FROM task vi\n                          WHERE vi.id = sp.task_id AND vi.task_type IN (%s, %s)\n                        ) THEN %s\n                        WHEN EXISTS (\n                          SELECT 1 FROM task vi\n                          WHERE vi.id = sp.task_id AND vi.task_type = 'ppt'\n                        ) THEN %s\n                        ELSE %s\n                      END\n                  AND sp.status = %s\n                ", (_core.RUNNING, *recycled_failed_task_ids, _core.SPEAKER_NARRATION_SUB_STAGE, *_core.CHUNK_SPEAKER_TASK_TYPES, _core.SPEAKER_DUBBING_MULTI_SEGMENT_SUB_STAGE, _core.SPEAKER_PPT_DIALOGUE_SUB_STAGE, _core.SPEAKER_MAIN_SUB_STAGE, _core.FAILED))
        conn.commit()
        return (int(retried) + int(failed) + int(recycled_failed), exhausted_task_ids)
